version: "3.8"

services:
  mud:
    image: scionaltera/agonyforge-mud-demo:latest
    tty: true
#    ports:
#      - "8080:8080"
#      - "5005:5005"
    ports:
      - "8080"
    env_file:
      - mud.env

  dynamodb:
    image: amazon/dynamodb-local
    volumes:
      - ./volume:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  # credit to https://aws.plainenglish.io/run-aws-dynamodb-locally-2788ad73c4db for this one
  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - dynamodb
    environment:
      AWS_ACCESS_KEY_ID: x
      AWS_SECRET_ACCESS_KEY: x
      AWS_REGION: us-west-2
      AWS_ENDPOINT: "--endpoint-url http://dynamodb:8000"
      AWS_MAX_ATTEMPTS: 10
    entrypoint: /bin/sh -c
    volumes:
      - './agonyforge-mud-models-dynamodb/src/main/bash:/init-scripts'
    command: >
      '
      for script_name in /init-scripts/*.sh; do
        sh $$script_name
      done
      '

  activemq:
    image: symptoma/activemq:5.17.1-envvars
    ports:
      - "127.0.0.1:61613:61613"
      - "127.0.0.1:8161:8161"
    environment:
      ACTIVEMQ_WEBCONSOLE_USE_DEFAULT_ADDRESS: "false"

      # user with access to web UI
      ACTIVEMQ_WEBADMIN_USERNAME: admin
      ACTIVEMQ_WEBADMIN_PASSWORD: admin

      # user with access to broker
      ACTIVEMQ_USERNAME: mud
      ACTIVEMQ_PASSWORD: mud
