version: "3.8"

services:
  mud:
    image: scionaltera/agonyforge-mud-demo:latest
    tty: true
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - mud.env

  dynamodb:
    image: amazon/dynamodb-local
    volumes:
      - ./volume:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  activemq:
    image: symptoma/activemq:5.17.1-envvars
    ports:
      - "127.0.0.1:61613:61613"
      - "127.0.0.1:8161:8161"
    environment:
      ACTIVEMQ_WEBCONSOLE_USE_DEFAULT_ADDRESS: "false"

      # user with access to web UI
      ACTIVEMQ_WEBADMIN_USERNAME: admin
      ACTIVEMQ_WEBADMIN_PASSWORD: admin

      # user with access to broker
      ACTIVEMQ_USERNAME: mud
      ACTIVEMQ_PASSWORD: mud
