AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Table for Agony Forge MUD
Parameters:
  TableName:
    Type: String
    Description: The name of the DynamoDB table to create.
Resources:
  DynamoMainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsipk1
          AttributeType: S
        - AttributeName: gsipk2
          AttributeType: S
        - AttributeName: ttl
          AttributeType: N
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
            - AttributeName: gsipk1
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: gsi2
          KeySchema:
            - AttributeName: gsipk2
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: 'True'
      TableName:
        Ref: TableName
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
