spring:
  jpa:
    open-in-view: false
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true

server:
  error:
    path: /error
  tomcat:
    accesslog:
      enabled: true
      buffered: false
    redirect-context-root: false

logging:
  level:
    com:
      agonyforge:
        mud:
          core:
            # displays access logs in the regular logs
            # may cause performance issues if used on servers with lots of traffic
            logging: DEBUG
#      hibernate:
#        type: TRACE
