spring:
  jpa:
    open-in-view: false
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true

server:
  tomcat:
    accesslog:
      enabled: true
      buffered: false
    redirect-context-root: false

logging:
  level:
    com:
      agonyforge:
        mud:
          core:
            logging: DEBUG
#    org:
#      apache:
#        tomcat: DEBUG
#        catalina: DEBUG
#      hibernate:
#        type: TRACE
